name: Build on Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install pyenv-win
      run: Invoke-WebRequest -UseBasicParsing -Uri "https://raw.githubusercontent.com/pyenv-win/pyenv-win/master/pyenv-win/install-pyenv-win.ps1" -OutFile "./install-pyenv-win.ps1"; &"./install-pyenv-win.ps1"

    - name: Setup pyenv and Python environment
      run: |
        $env:PATH = "$env:USERPROFILE\.pyenv\pyenv-win\bin;$env:USERPROFILE\.pyenv\pyenv-win\shims;$env:PATH"
        pyenv install $(Get-Content .python-version)
        pyenv local $(Get-Content .python-version)
        pyenv exec python -m venv venv

    - name: Install dependencies
      run: |
        .\venv\Scripts\activate.ps1
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Create the executable
      run: |
        .\venv\Scripts\activate.ps1
        pyinstaller --onedir --add-data "adbutils;adbutils" --add-data "img;img" --add-data "venv/Lib/site-packages/scrcpy/scrcpy-server.jar;scrcpy" AutoAFK2.py
        cp .\settings.ini .\dist\AutoAFK2\

    - name: Zip the dist directory
      run: Compress-Archive -Path .\dist\AutoAFK2\* -DestinationPath AutoAFK2.zip

    - name: Upload the ZIP to the release
      uses: softprops/action-gh-release@v2
      with:
        files: AutoAFK2.zip
